name = "tct-portfolio"
main = "dist"
compatibility_date = "2025-11-03"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "citas_tct"
database_id = "7fc23920-1511-4a3b-90a3-6975e7634eed"
